// <auto-generated />
using JTC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JTC.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("JTC.Data.Entities.GuildEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("JTC.Data.Entities.HubEntity", b =>
                {
                    b.Property<ulong>("VoiceChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TemporaryVoiceChannelInterface")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoiceChannelId");

                    b.HasIndex("GuildId");

                    b.ToTable("Hubs");
                });

            modelBuilder.Entity("JTC.Data.Entities.TemporaryVoiceChannelEntity", b =>
                {
                    b.Property<ulong>("VoiceChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("HubVoiceChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoiceChannelId");

                    b.HasIndex("HubVoiceChannelId");

                    b.ToTable("TemporaryVoiceChannels");
                });

            modelBuilder.Entity("JTC.Data.Entities.HubEntity", b =>
                {
                    b.HasOne("JTC.Data.Entities.GuildEntity", null)
                        .WithMany("Hubs")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JTC.Data.Entities.TemporaryVoiceChannelEntity", b =>
                {
                    b.HasOne("JTC.Data.Entities.HubEntity", null)
                        .WithMany("TemporaryVoiceChannels")
                        .HasForeignKey("HubVoiceChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JTC.Data.Entities.GuildEntity", b =>
                {
                    b.Navigation("Hubs");
                });

            modelBuilder.Entity("JTC.Data.Entities.HubEntity", b =>
                {
                    b.Navigation("TemporaryVoiceChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
